<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>eo</string>
	</array>
	<key>name</key>
	<string>eo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\+(package|alias|architect) .*</string>
			<key>name</key>
			<string>meta.eo</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#square</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\#.*$</string>
					<key>name</key>
					<string>comment.line.eo</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(TRUE|FALSE)\b</string>
					<key>name</key>
					<string>constant.language.eo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([1-9]+[0-9]*|0)</string>
					<key>name</key>
					<string>constant.numeric.int.eo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(\d+e[\-\+]?\d+)</string>
					<key>name</key>
					<string>constant.numeric.float.eo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([0-9A-F][0-9A-F](\-[0-9A-F][0-9A-F])*)\b</string>
					<key>name</key>
					<string>constant.numeric.bytes.eo</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string> &gt; </string>
					<key>name</key>
					<string>keyword.operator.bound.eo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.\.\.</string>
					<key>name</key>
					<string>keyword.operator.vararg.eo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>keyword.operator.dot.eo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\!</string>
					<key>name</key>
					<string>keyword.operator.constant.eo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\&amp;</string>
					<key>name</key>
					<string>keyword.operator.home.eo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\^</string>
					<key>name</key>
					<string>keyword.operator.parent.eo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$</string>
					<key>name</key>
					<string>keyword.operator.current.eo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@</string>
					<key>name</key>
					<string>keyword.operator.decorator.eo</string>
				</dict>
			</array>
		</dict>
		<key>parens</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code</string>
				</dict>
			</array>
		</dict>
		<key>square</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.eo</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.eo</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.eo</string>
        <key>uuid</key>
	<string>CD8BC55C-09A2-427E-BC55-C1673D596D41</string>
</dict>
</plist>
